import type { SnapCase } from '../types';
import { evaluateEligibility, ELIGIBILITY_DISCLAIMER } from './eligibility';

export function generateCaseSummary(c: SnapCase): string {
  const eligibility = evaluateEligibility(c);
  const received = c.documents.filter((d) => d.status === 'received').map((d) => d.label);
  const missing = c.documents.filter((d) => d.required && d.status === 'missing').map((d) => d.label);
  const needsReview = c.documents
    .filter((d) => d.status === 'needs review' || d.status === 'possible mismatch')
    .map((d) => `${d.label} (${d.status}${d.note ? `: ${d.note}` : ''})`);

  const flagsHigh = c.riskFlags.filter((f) => f.severity === 'high');
  const flagsOther = c.riskFlags.filter((f) => f.severity !== 'high');

  let nextAction = 'Route to caseworker for review.';
  if (eligibility === 'expedited review recommended') {
    nextAction = 'Route to expedited review queue. Federal expedited service rules may apply.';
  } else if (missing.length > 0) {
    nextAction = `Request missing documents: ${missing.join(', ')}.`;
  } else if (flagsHigh.length > 0) {
    nextAction = 'Hold for human review — high-severity risk indicator(s) present. Do not deny benefits automatically.';
  } else if (needsReview.length > 0) {
    nextAction = 'Route to human document reviewer for mismatch confirmation.';
  } else if (eligibility === 'likely eligible') {
    nextAction = 'Forward to caseworker for final eligibility determination.';
  }

  const lines: string[] = [];
  lines.push(`CASE SUMMARY — ${c.id}`);
  lines.push(`Generated by SNAP AI (decision support only)`);
  lines.push('');
  lines.push('APPLICANT OVERVIEW');
  lines.push(`  Name: ${c.applicantName}`);
  lines.push(`  Address: ${c.address}`);
  lines.push(`  County: ${c.county}`);
  lines.push(`  Employment: ${c.employmentStatus}`);
  lines.push(`  Monthly income (reported): $${c.income.toLocaleString()}`);
  lines.push(`  Emergency need indicated: ${c.emergencyNeed ? 'Yes' : 'No'}`);
  lines.push('');
  lines.push('HOUSEHOLD COMPOSITION');
  lines.push(`  Household size: ${c.householdSize}`);
  c.householdMembers.forEach((m) => {
    const tags = [
      m.isStudent ? 'student' : null,
      m.isDisabled ? 'disabled' : null,
      m.isElderly ? 'elderly' : null,
    ].filter(Boolean).join(', ');
    lines.push(
      `  - ${m.name} (age ${m.age}, ${m.relationship}) — income $${m.income.toLocaleString()}${tags ? ` [${tags}]` : ''}`,
    );
  });
  lines.push('');
  lines.push('DOCUMENTS RECEIVED');
  if (received.length === 0) lines.push('  (none)');
  received.forEach((d) => lines.push(`  - ${d}`));
  lines.push('');
  lines.push('MISSING / NEEDS REVIEW');
  if (missing.length === 0 && needsReview.length === 0) lines.push('  None — required documents on file.');
  missing.forEach((d) => lines.push(`  - MISSING: ${d}`));
  needsReview.forEach((d) => lines.push(`  - REVIEW: ${d}`));
  lines.push('');
  lines.push('RISK INDICATORS');
  if (c.riskFlags.length === 0) lines.push('  No flags raised by automated screening.');
  flagsHigh.forEach((f) => lines.push(`  - [HIGH] ${f.type}: ${f.detail} — Requires human review.`));
  flagsOther.forEach((f) => lines.push(`  - [${f.severity.toUpperCase()}] ${f.type}: ${f.detail}`));
  lines.push('');
  lines.push('PRE-SCREEN RESULT');
  lines.push(`  ${eligibility.toUpperCase()}`);
  lines.push('');
  lines.push('RECOMMENDED NEXT ACTION');
  lines.push(`  ${nextAction}`);
  lines.push('');
  lines.push(`Disclaimer: ${ELIGIBILITY_DISCLAIMER}`);

  return lines.join('\n');
}
